import { useState, useEffect, useRef } from 'react';
import { supabase } from '../lib/supabase';
interface Comment { id:string; body:string; author_name:string|null; timestamp_ms:number|null; created_at:string; profiles?:{display_name:string|null}|null; }
function fmtMs(ms:number|null){if(ms===null)return null;const s=Math.floor(ms/1000);return `${Math.floor(s/60)}:${(s%60).toString().padStart(2,'0')}`;}
function timeAgo(iso:string){const d=Date.now()-new Date(iso).getTime();const m=Math.floor(d/60000);if(m<1)return 'just now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`;}
interface CommentsPanelProps {
  versionId: string;
  shareLinkId?: string;
  allowComments: boolean;
  positionMs: number;
  onSeek: (ms:number)=>void;
  layout?: 'sidebar' | 'full' | 'horizontal';
}
export function CommentsPanel({versionId,allowComments,positionMs,onSeek,layout='sidebar'}:CommentsPanelProps){
  const isFull = layout === 'full' || layout === 'horizontal';
  const [comments,setComments]=useState<Comment[]>([]);
  const [body,setBody]=useState('');const [name,setName]=useState('');const [stamp,setStamp]=useState(true);const [sending,setSending]=useState(false);
  const bottomRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{supabase.from('comments').select('id,body,author_name,timestamp_ms,created_at,profiles(display_name)').eq('version_id',versionId).order('created_at',{ascending:true}).then(({data})=>{if(data)setComments(data as Comment[]);});},[versionId]);
  useEffect(()=>{const ch=supabase.channel(`comments:${versionId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'comments',filter:`version_id=eq.${versionId}`},p=>{setComments(c=>[...c,p.new as Comment]);setTimeout(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),50);}).subscribe();return()=>{supabase.removeChannel(ch);};},[versionId]);
  const submit=async()=>{if(!body.trim()||sending)return;setSending(true);await supabase.from('comments').insert({version_id:versionId,body:body.trim(),author_name:name.trim()||'Anonymous',timestamp_ms:stamp?Math.round(positionMs):null});setBody('');setSending(false);};
  const p:Record<string,React.CSSProperties>={panel:{display:'flex',flexDirection:'column',borderLeft:isFull?'none':'0.5px solid rgba(255,255,255,0.07)',width:isFull?'100%':240,flexShrink:0,fontFamily:"'Syne',sans-serif",background:isFull?'rgba(255,255,255,0.03)':undefined,borderRadius:isFull?16:undefined,padding:isFull?20:undefined, ...(layout==='horizontal'?{maxWidth:'100%',width:'100%',borderRadius:24,background:'rgba(255,255,255,0.03)',padding:20,marginTop:12}:{}),},header:{padding:isFull?'16px 18px 12px':'14px 16px 10px',fontSize:11,fontWeight:700,letterSpacing:'0.1em',color:'rgba(232,228,220,0.35)',textTransform:'uppercase',display:'flex',alignItems:'center',gap:8,borderBottom:isFull?'0.5px solid rgba(255,255,255,0.08)':'0.5px solid rgba(255,255,255,0.07)'},list:{flex:1,overflowY:'auto',padding:isFull?'16px 18px 10px':'10px 16px'},comment:{marginBottom:16},meta:{display:'flex',alignItems:'center',gap:8,marginBottom:3},name:{fontSize:11,fontWeight:700,color:'rgba(232,228,220,0.7)'},ts:{background:'rgba(201,245,94,0.08)',border:'0.5px solid rgba(201,245,94,0.2)',borderRadius:3,padding:'1px 6px',fontSize:10,color:'#c9f55e',cursor:'pointer',fontFamily:"'DM Mono',monospace"},ago:{fontSize:10,color:'rgba(232,228,220,0.25)',marginLeft:'auto',fontFamily:"'DM Mono',monospace"},cbody:{fontSize:12,color:'rgba(232,228,220,0.5)',lineHeight:1.45,margin:0},input:{padding:'10px 14px',width:'100%',marginBottom:8,background:'rgba(255,255,255,0.04)',border:'0.5px solid rgba(255,255,255,0.1)',borderRadius:6,color:'#e8e4dc',fontSize:12,fontFamily:"'Syne',sans-serif",outline:'none',boxSizing:'border-box'},inputArea:{padding:'10px 14px 14px',borderTop:'0.5px solid rgba(255,255,255,0.07)'},row:{display:'flex',gap:6},ta:{flex:1,padding:'7px 10px',resize:'none',background:'rgba(255,255,255,0.04)',border:'0.5px solid rgba(255,255,255,0.1)',borderRadius:6,color:'#e8e4dc',fontSize:12,fontFamily:"'Syne',sans-serif",outline:'none'},send:{background:'rgba(201,245,94,0.1)',border:'0.5px solid rgba(201,245,94,0.25)',borderRadius:6,padding:'0 12px',color:'#c9f55e',fontSize:16,cursor:'pointer',alignSelf:'stretch'},lbl:{display:'flex',alignItems:'center',marginTop:8,fontSize:11,color:'rgba(232,228,220,0.3)',cursor:'pointer'}};
  return <div style={p.panel}><div style={p.header}>Comments <span style={{background:'rgba(255,255,255,0.07)',borderRadius:4,padding:'1px 6px',fontSize:10}}>{comments.length}</span></div><div style={p.list}>{comments.length===0&&<p style={{fontSize:12,color:'rgba(232,228,220,0.25)',textAlign:'center',marginTop:24}}>No comments yet.</p>}{comments.map(c=><div key={c.id} style={p.comment}><div style={p.meta}><span style={p.name}>{c.profiles?.display_name??c.author_name??'Anonymous'}</span>{c.timestamp_ms!==null&&<button style={p.ts} onClick={()=>onSeek(c.timestamp_ms!)}>@ {fmtMs(c.timestamp_ms)}</button>}<span style={p.ago}>{timeAgo(c.created_at)}</span></div><div style={p.cbody}>{c.body}</div></div>)}<div ref={bottomRef}/></div>{allowComments&&<div style={p.inputArea}><input style={p.input} placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/><div style={p.row}><textarea style={p.ta} placeholder="Leave a note..." value={body} rows={2} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey))submit();}}/><button style={p.send} onClick={submit} disabled={sending||!body.trim()}>{sending?'…':'↑'}</button></div></div>}</div>;
}
